### PR TITLE
Create Plugin: Update Jest to v29

### LINKED ISSUE #161: Create Plugin: Update to Jest 29
We're still running Jest 27. Would be nice to update to latest before the v1.0.0 release.

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
The version of jest offered with create-plugin is two major versions behind current. This PR updates it to latest (v29) inline with Grafana core.

**Which issue(s) this PR fixes**:

Fixes #161

**Special notes for your reviewer**:
I've not tested this yet. Hoping CI can pick up anything obvious first.

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/create-plugin@0.8.0-canary.164.d94943e.0
  # or 
  yarn add @grafana/create-plugin@0.8.0-canary.164.d94943e.0
  ```
</details>

### CODE REVIEW

**Review by leventebalogh — APPROVED** [review]
LGTM 👍 

(Haven't tested it locally, just based on the code.)

**Comment by leventebalogh** [comment]
Actually, just tested it out and it didn't work for me unfortunately (latest published version works):

Screenshot 2022-11-30 at 10 33 45

**Comment by leventebalogh** [comment]
Another thing that is not directly related to this PR but maybe something we should include in our "What's next?" paragraph.
Once I generated the plugin, did `yarn install` and try to run `yarn test` it fails due to not having Git initialised.

```
--watch is not supported without git/hg
```

We could either just use `--watchAll` instead of `--watch --onlyChanged`, or we can add a point in the "What's next?" section to raise their attention to initialise Git before doing anything else.

**Comment by jackw** [comment]
Thanks for taking the time to test this out @leventebalogh really appreciate it. I've pushed a couple of commits that should fix the errors with tests and improve our success messaging...


Screenshot 2022-11-30 at 12 37 03

**Pull request merged**
