### PR TITLE
Docs: Add template variables content

### LINKED ISSUE #70943: Docs: Template Variables guide and advanced examples for plugins
**Why?**

We need better documentation on how to use template variables in plugins as this is an area where we get a lot of questions and very few expertise in our squad.

**How?**
We already have initial docs [here](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/) 
and we have our community post with more advanced use cases [here](https://community.grafana.com/t/how-to-use-template-variables-in-your-data-source/63250)

```[tasklist]
### Tasks
- [x] Start by merging the content of what we have in our forum  into the docs
- [ ] Add "How to interpolate variable named X into a query value named Y (with different name)"
- [ ] Add "How to inject the variable label in query editor input fields"
- [ ] Add more as you see fit / check out other requests we got over time
```

### PR DESCRIPTION
**Pull request by josmperez**
Add docs for template variables to existing doc on variables. Specific changes:
- Add content from https://community.grafana.com/t/how-to-use-template-variables-in-your-data-source/63250
- Replace content on multi-variable support with community forum content
- Restructure content slightly
- Fix broken link and minor editorial tweaks

Fixes https://github.com/grafana/grafana/issues/70943

### CODE REVIEW

**Comment by sunker** [comment]
Looks like a great start @josmperez! A few things have changed since Marcus wrote that post on the community site. Would be good to have a discussion around the variable apis before publishing this, so I started a convo in our team slack. 

I'd be happy to help out adding missing pieces here as soon as we reach to a conclusion on how to use variables in plugins.

**Comment by josmperez** [comment]
Hi @sunker - I appreciate your willingness to edit this content or draft new content for this PR. Have you started this yet? If not, could you please let me know when I might see revisions? Thanks.

**Comment by sunker** [comment]
> Hi @sunker - I appreciate your willingness to edit this content or draft new content for this PR. Have you started this yet? If not, could you please let me know when I might see revisions? Thanks.

Hi @josmperez. I'm afraid I need to focus on a other things right now. Can't say for sure, but hopefully I can start with this in a month of time.

**Comment by josmperez** [comment]
@sunker - I know you've been busy with writing docs and other things. Do you think this is do-able for Q1?

**Review by mckn — COMMENTED** [review]
I think this is a great improvement!

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by josmperez** [comment]
Because of its age and conflicts with the reorganization of the site, this PR is closed in favor of https://github.com/grafana/plugin-tools/pull/1096

**Pull request closed without merging**
