### PR TITLE
Website: Add a DocLinkList component

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Minimises the space taken up by "index" pages and prevents truncation of descriptions.

## before
Screenshot 2023-10-25 at 14 57 26

## after
Screenshot 2023-10-25 at 14 56 01

**Which issue(s) this PR fixes**:

Related #473

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by sympatheticmoose** [comment]
@jackw so to use this we'd just replace `<DocCardList />` with `<DocLinkList />` for the current indexes?

**Review by sympatheticmoose — APPROVED** [review]
I like 😄 but definitely lets wait for Joe's input. 

I also wonder whether we should start documenting things like this either in https://github.com/grafana/plugin-tools/blob/main/CONTRIBUTING.md#contribute-documentation or https://github.com/grafana/plugin-tools/blob/main/docusaurus/website/README.md

**Comment by jackw** [comment]
> @jackw so to use this we'd just replace `<DocCardList />` with `<DocLinkList />` for the current indexes?

Exactly and as it's also added to the `theme/MDXcomponents` file there is no need to import it in the current indexes. 👍

**Review by josmperez — APPROVED** [review]
Love it!

**Pull request merged**
