### PR TITLE
Replace `wait for` docker call with our custom github action

### PR DESCRIPTION
**Pull request by academo**
**What this PR does / why we need it**:

Alternative to https://github.com/grafana/plugin-tools/pull/1215

in this version we replace the docker call with a custom bash script

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Depends on https://github.com/grafana/plugin-actions/pull/39

This PR CI will fail until the previous PR is merged.

### CODE REVIEW

**Comment by tolzhabayev** [comment]
Screenshot 2024-10-15 at 11 38 10

https://github.com/grafana/plugin-tools/actions/runs/11342327498/job/31542524554?pr=1219#step:15:12

**Review by xnyo — APPROVED** [review]
LGTM! 🙌

**Review by leventebalogh — APPROVED** [review]

**Comment by xnyo** [comment]
Do we also want to update the developer docs for consistency?

- https://github.com/grafana/plugin-tools/blob/d48f90b01f66e17308a1e260cccc58d43bad92ad/docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md?plain=1#L64
- https://github.com/grafana/plugin-tools/blob/d48f90b01f66e17308a1e260cccc58d43bad92ad/docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md?plain=1#L64

**Review by sunker — APPROVED** [review]
Nice 👏 

FYI [this](https://github.com/grafana/plugin-tools/pull/1223) PR should solve the broken e2e tests in dev.

**Comment by tolzhabayev** [comment]
@academo go for merge?

**Pull request merged**
