### PR TITLE
Docs: Add RBAC guide for app plugins

### LINKED ISSUE #988: Docs: Create page detailing how plugins can use RBAC
### Which areas does this feature request relate to

- [ ] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor
- [X] Documentation

### Problem

There is no docs page that details how a plugin developer can use RBAC in their plugin.

### Solution

Create a page in our docs website that explains how developers can use this feature. The [rbac example readme](https://github.com/grafana/grafana-plugin-examples/blob/main/examples/app-with-rbac/README.md) is quite extensive and could likely be used as reference. We could probably align this with the release of the new RBAC frontend interface due in Grafana 11.2.0.

### Alternatives

_No response_

### Additional context

_No response_

### Are you interested in contributing the solution?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by tomglenn**
Migrates and reworks the RBAC guide for app plugins from https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-rbac

Fixes #988

**Special notes for your reviewer**: Please do not merge until Grafana 11.2.0 release.

### CODE REVIEW

**Comment by tomglenn** [comment]
I will create an RBAC guide for Datasource plugins separately after speaking with @ckbedwell on requirements.

**Review by josmperez — CHANGES_REQUESTED** [review]
Very nice work. I've taken a first editorial pass on the doc and found some minor issues. Fixed them in my commits today, but take a look. I'll take a second pass after the PR is out of draft state.

**Comment by josmperez** [comment]
> Migrates and reworks the RBAC guide for app plugins from [grafana/grafana-plugin-examples@`main`/examples/app-with-rbac](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-rbac?rgh-link-date=2024-07-19T11%3A38%3A30Z)

Could you please clarify what "migrates and reworks" means? Specifically, how does this how-to guide harmonize with the existing README? Does the README need to be rewritten? Is there duplicate content there that will need to be removed?

**Comment by tomglenn** [comment]
> > Migrates and reworks the RBAC guide for app plugins from [grafana/grafana-plugin-examples@`main`/examples/app-with-rbac](https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-rbac?rgh-link-date=2024-07-19T11%3A38%3A30Z)
> 
> Could you please clarify what "migrates and reworks" means? Specifically, how does this how-to guide harmonize with the existing README? Does the README need to be rewritten? Is there duplicate content there that will need to be removed?

The existing README is based on the old method of checking permissions in the frontend using `contextSrv.hasPermission` rather than the new `hasPermission` function from `@grafana/runtime` (see @jackw's open PR for the changes to the example code here https://github.com/grafana/grafana-plugin-examples/compare/main...jackw%2Fmigrate-rbac-runtime).

The example README should be updated to reflect the changes (perhaps part of that same PR @jackw).

With regards to the rework portion, I've re-worded and expanded (added context) the contents from the README to be more fitting for the docs.

**Comment by tomglenn** [comment]
> Very nice work. I've taken a first editorial pass on the doc and found some minor issues. Fixed them in my commits today, but take a look. I'll take a second pass after the PR is out of draft state.

Edits look good to me 👍

**Review by mckn — APPROVED** [review]
LGTM!

**Review by leventebalogh — APPROVED** [review]
Nice! 👏

**Comment by tomglenn** [comment]
Thanks all. @josmperez if you're happy then we can merge this.

**Review by josmperez — APPROVED** [review]

**Pull request merged**
