### PR TITLE
Fix: include uppercase characters when normalising plugin id

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Users can type all sorts into the prompts when scaffolding a new plugin. Right now the `normalizeId` function strips uppercase characters which creates incorrect IDs (see path of directory created below):

```
success Installed "@grafana/create-plugin@0.5.0" with binaries:
      - create-plugin
? What is going to be the name of your plugin? My Plugin
? What is the organization name of your plugin? HeyWesty
? How would you describe your plugin?
? What kind of plugin would you like?  panel
? Do you want to add Github CI and Release workflows? Yes
? Do you want to add a Github workflow for automatically checking "Grafana API compatibility" on PRs? Yes
✔  ++ /Users/jackwestbrook/Sandbox/plugin-tools-tests/eyesty-ylugin-panel/.config/.eslintrc
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/create-plugin@0.5.1-canary.142.d32fe7f.0
  # or 
  yarn add @grafana/create-plugin@0.5.1-canary.142.d32fe7f.0
  ```
</details>

### CODE REVIEW

**Comment by tolzhabayev** [comment]
Should'nt we instead `.toLowerCase()` them?

**Comment by tolzhabayev** [comment]
I think we should in:
- `normalize_id` make everything lowecase as we use it in plugin.json -> id which is the plugin slug, that has to be lowecase, no spaces, etc. https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/panel/src/plugin.json#L5
- Outside of `normalize_id` orgName being any case should be allowed https://github.com/grafana/plugin-tools/blob/main/packages/create-plugin/templates/panel/src/plugin.json#L10
- Same for `pluginName` it can be any case

**Review by leventebalogh — COMMENTED** [review]
LGTM 👍 

Why are we using the `change-case`, `upper-case`, etc packages instead of `string.toLowerCase()`? To cater for some unicode character mappings?

Nit: maybe we could just return with this?
```javascript
return changeCase.lowerCase(`${newOrgName}-${newPluginName}-${type}`);
```

**Review by tolzhabayev — CHANGES_REQUESTED** [review]
see above

**Review by tolzhabayev — APPROVED** [review]
forget about my messages above, we already do lowercase in return

**Review by leventebalogh — APPROVED** [review]

**Pull request merged**
