### PR TITLE
Copy over `query_help.md` when building plugins

### PR DESCRIPTION
**Pull request by mure**
**What this PR does / why we need it**:

Data sources can expose plugin help in markdown: https://github.com/grafana/grafana/blob/546b2deb13ae5d86c03dbd5e639cf0c90296ce42/public/app/core/components/PluginHelp/PluginHelp.tsx#L14

But the webpack config in this repo doesn't copy it over when building.

**Special notes for your reviewer**:

I tested this with an app plugin with nested data sources.

### CODE REVIEW

**Review by jackw — APPROVED** [review]
LGTM! 🚀 

Apologies for the slow turnaround here @mure . We really appreciate you taking the time to fix this issue . 👏👏👏

**Comment by academo** [comment]
@jackw can we merge this PR?

**Review by leventebalogh — APPROVED** [review]
LGTM 👍

**Comment by mountainash** [comment]
This PR breaks prettier `true}` is missing a space. /cc @mure 

[{ from: '**/query_help.md', to: '.', noErrorOnMissing: true}, // Optional](https://github.com/grafana/plugin-tools/blob/6502c154ca1413eccac300b61927e6edc3a1f8bc/packages/create-plugin/templates/common/.config/webpack/webpack.config.ts#L160-L161)

**Pull request merged**
