### PR TITLE
Docs: fix backend developer resources link

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
The link from get-started to backend developer resources appears to randomly break. I believe it's caused by the period at the start of the link.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by sympatheticmoose — APPROVED** [review]
🚀

**Review by sympatheticmoose — CHANGES_REQUESTED** [review]
Screenshot 2023-10-18 at 16 09 32

Just noticed an issue

**Comment by josmperez** [comment]
What does {' '} do? I was getting a compilation error for me today and eliminating it made the error go away.

**Review by josmperez — APPROVED** [review]
LGTM.

**Pull request merged**
