### PR TITLE
README typo fixes

### PR DESCRIPTION
**Pull request by aangelisc**

### CODE REVIEW

**Review by mckn — APPROVED** [review]
LGTM!

**Comment by sympatheticmoose** [comment]
Assuming Joe is happy with the change, please could you also update our docs for the ESM error? https://github.com/grafana/plugin-tools/blob/main/docusaurus/docs/troubleshooting.md

**Review by josmperez — COMMENTED** [review]
LGTM.

**Comment by josmperez** [comment]
> Assuming Joe is happy with the change, please could you also update our docs for the ESM error?

LGTM.

**Pull request merged**
