### PR TITLE
Bumping workflow version to use node 16 instead of deprecated node 12

### PR DESCRIPTION
**Pull request by tolzhabayev**
**What this PR does / why we need it**:

Removes this deprecation warning, which you can see [here](https://github.com/grafana/plugin-tools/actions/runs/3460203067)

SCR-20221114-f44

### CODE REVIEW

**Comment by tolzhabayev** [comment]
🤔 what labels are correct in this case?

**Review by leventebalogh — APPROVED** [review]
LGTM 👍

**Comment by leventebalogh** [comment]
I guess we should have a `chore` label or something similar? 🤔

**Comment by jackw** [comment]
> 🤔 what labels are correct in this case?

In regard to a release label? We shouldn't need any labels. It'll be ignored as it doesn't affect any of the packages.

> I guess we should have a chore label or something similar? 🤔

Have added one and attached it to this PR!

**Review by jackw — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
